[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.25"
optimizer = true
optimizer_runs = 200
via_ir = false
evm_version = "cancun"
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@solmate/=lib/solmate/src/",
]

[rpc_endpoints]
rayls_devnet = "https://devnet-rpc.rayls.com"

[etherscan]
rayls_devnet = { api_url = "https://devnet-explorer.rayls.com/api", key = "" }

